### ISSUE TITLE
py-build error

### ISSUE THREAD

**Issue by Zearin** [ccpgames/pypackage#10]
Here is a recent terminal session I had using `py-build`: 

```
$ py-build -i
pypackage has guessed the following attributes:
1 `name` = "cucumber-python"
2 `version` = "0.0.1"
3 `package_data` = "['DS_Store', 'editorconfig', 'CHANGELOG.md', 'LICENSE', 'package.json', 'README.md', 'idea/.name', 'idea/cucumber-python.iml', 'idea/encodings.xml', 'idea/misc.xml', 'idea/modules.xml', 'idea/vcs.xml', 'idea/workspace.xml', 'idea/dictionaries/<USER>.xml', 'idea/inspectionProfiles/profiles_settings.xml', 'idea/inspectionProfiles/Project_Default.xml', 'features/hello.feature']"
would you like to disregard any of the above guesses?
use 1-3 or "all" to ignore (enter to accept): 3
package_data will not be guessed
use 1-3 or "all" to ignore (enter to accept): 3
package_data will not be guessed
use 1-3 or "all" to ignore (enter to accept): 
Starting interactive build for cucumber...
~~~~~~~~~ Standard Attributes ~~~~~~~~~~
Please enter the value for author_email: 
Please enter the value for maintainer_email: 
Please enter the value for url: 
Please enter the value for download_url: 
Please enter the value for py_modules: 
Please enter the value for scripts: 
~~~~~~~~~~ Pypackage Features ~~~~~~~~~~
Please enter the value for runner_args: 
Please enter the value for source_label: 
Please enter the value for source_url: 
Traceback (most recent call last):
  File "/Users/<USER>/Developer/Projects/GitHub/cucumber-python/_venv/bin/py-build", line 11, in <module>
    sys.exit(build())
  File "/Users/<USER>/Developer/Projects/GitHub/cucumber-python/_venv/lib/python3.5/site-packages/pypackage/commands.py", line 68, in build
    pypackage_setup(build_commands, options=options, additional=build.__doc__)
  File "/Users/<USER>/Developer/Projects/GitHub/cucumber-python/_venv/lib/python3.5/site-packages/pypackage/__init__.py", line 68, in pypackage_setup
    with ManifestContext(config, options):   # write the MANIFEST.in
  File "/Users/<USER>/Developer/Projects/GitHub/cucumber-python/_venv/lib/python3.5/site-packages/pypackage/context.py", line 72, in __enter__
    for _, files in getattr(self.config, "data_files", []):
ValueError: not enough values to unpack (expected 2, got 0)
```

Looks like it it choked on an empty list.  Probably should be a no-op.

**Comment by a-tal** [comment]
can you try 0.2.2? I think this is from having malformed a data_files value in your meta.

**Comment by a-tal** [comment]
assuming this is resolved in latest. feel free to open another issue or just reply here if it's not
